## 모두를 위한 머신러닝/딥러닝 강의
김성훈 교수님의 모두를 위한 머신러닝/딥러닝 강의 중 lab 강의 코드입니다.
## Lab4_1 Multi-variable linear regression

### Without numpy

In [1]:
import tensorflow as tf
tf.set_random_seed(777) # for reproducibility

x_data = [[73., 80., 75.], [93., 88., 93.],
          [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None])

W = tf.Variable(tf.random_normal(shape = [3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
opt = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = opt.minimize(cost)

# Launch the graph in a session
sess = tf.Session()

# Intializes global variables in the graph
sess.run(tf.global_variables_initializer())

for iter in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X : x_data, Y : y_data})
    if iter % 200 == 0:
        print(iter, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)

0 Cost:  22703.0 
Prediction:
 [[ 22.04806328]
 [ 21.61978722]
 [ 24.09669304]
 [ 22.29302025]
 [ 18.6339016 ]]
200 Cost:  797.905 
Prediction:
 [[ 153.15869141]
 [ 179.60064697]
 [ 179.56481934]
 [ 191.45135498]
 [ 139.35153198]]
400 Cost:  794.066 
Prediction:
 [[ 152.97161865]
 [ 179.74481201]
 [ 179.52754211]
 [ 191.26742554]
 [ 139.67353821]]
600 Cost:  790.376 
Prediction:
 [[ 152.79785156]
 [ 179.87974548]
 [ 179.49424744]
 [ 191.08711243]
 [ 139.98278809]]
800 Cost:  786.822 
Prediction:
 [[ 152.63670349]
 [ 180.00598145]
 [ 179.46472168]
 [ 190.91033936]
 [ 140.27996826]]
1000 Cost:  783.393 
Prediction:
 [[ 152.48747253]
 [ 180.1239624 ]
 [ 179.43875122]
 [ 190.73684692]
 [ 140.56567383]]
1200 Cost:  780.077 
Prediction:
 [[ 152.34951782]
 [ 180.23413086]
 [ 179.41610718]
 [ 190.56654358]
 [ 140.84051514]]
1400 Cost:  776.866 
Prediction:
 [[ 152.22221375]
 [ 180.33691406]
 [ 179.39666748]
 [ 190.39929199]
 [ 141.10501099]]
1600 Cost:  773.751 
Prediction:
 [[ 152.10501099]
 

### With numpy 

In [2]:
# convert list to ndarray
import numpy as np
x_data = np.asarray(x_data)
y_data = np.asarray(y_data)

In [3]:
# placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None])

W = tf.Variable(tf.random_normal(shape = [3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
opt = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = opt.minimize(cost)

# Launch the graph in a session
sess = tf.Session()

# Intializes global variables in the graph
sess.run(tf.global_variables_initializer())

for iter in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X : x_data, Y : y_data})
    if iter % 200 == 0:
        print(iter, 'Cost: ', cost_val, '\nPrediction:\n', hy_val)

0 Cost:  9212.38 
Prediction:
 [[ 74.1805954 ]
 [ 80.63321686]
 [ 83.98022461]
 [ 91.3227005 ]
 [ 59.21071243]]
200 Cost:  893.798 
Prediction:
 [[ 154.68847656]
 [ 178.14100647]
 [ 179.68395996]
 [ 195.39904785]
 [ 133.88929749]]
400 Cost:  886.984 
Prediction:
 [[ 154.32833862]
 [ 178.40579224]
 [ 179.59617615]
 [ 195.1590271 ]
 [ 134.38607788]]
600 Cost:  880.562 
Prediction:
 [[ 153.99107361]
 [ 178.65478516]
 [ 179.51528931]
 [ 194.92486572]
 [ 134.86138916]]
800 Cost:  874.491 
Prediction:
 [[ 153.67546082]
 [ 178.88882446]
 [ 179.44091797]
 [ 194.69625854]
 [ 135.31640625]]
1000 Cost:  868.739 
Prediction:
 [[ 153.38035583]
 [ 179.10873413]
 [ 179.37272644]
 [ 194.47296143]
 [ 135.75215149]]
1200 Cost:  863.278 
Prediction:
 [[ 153.10464478]
 [ 179.31530762]
 [ 179.31037903]
 [ 194.25476074]
 [ 136.16963196]]
1400 Cost:  858.079 
Prediction:
 [[ 152.84729004]
 [ 179.50917053]
 [ 179.25352478]
 [ 194.04138184]
 [ 136.56976318]]
1600 Cost:  853.118 
Prediction:
 [[ 152.6072998 ]
 