## 모두를 위한 머신러닝/딥러닝 강의
김성훈 교수님의 모두를 위한 머신러닝/딥러닝 강의 중 lab 강의 코드입니다.
## Lab8 Tensor Manipulation

In [1]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint

tf.set_random_seed(777)  # for reproducibility
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

### Simple Array

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


### 2D Array

In [3]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


### Shape, Rank, Axis

In [4]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [5]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2])

In [6]:
t = tf.constant([[[[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]],
                  [[13, 14, 15, 16],
                   [17, 18, 19, 20],
                   [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [7]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

In [8]:
tmp = np.array([
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
])
print(tmp.shape, tmp.ndim, tmp.size)

(1, 2, 3, 4) 4 24


In [9]:
np.sum(tmp, axis = 0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [10]:
np.sum(tmp, axis = 1)

array([[[14, 16, 18, 20],
        [22, 24, 26, 28],
        [30, 32, 34, 36]]])

In [11]:
np.sum(tmp, axis = 2)

array([[[15, 18, 21, 24],
        [51, 54, 57, 60]]])

In [12]:
np.sum(tmp, axis = 3)

array([[[10, 26, 42],
        [58, 74, 90]]])

### Matmul VS multiply

#### example1

In [13]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).eval()

array([[ 12.]], dtype=float32)

In [14]:
tf.shape(matrix1).eval()

array([1, 2])

In [15]:
tf.shape(matrix2).eval()

array([2, 1])

#### example2

In [16]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])
print('matrix1 shape : {}'.format(matrix1.shape))
print('matrix2 shape : {}'.format(matrix2.shape))

tf.matmul(matrix1, matrix2).eval()

matrix1 shape : (2, 2)
matrix2 shape : (2, 1)


array([[  5.],
       [ 11.]], dtype=float32)

### Watch out broadcasting
참고 : https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

In [17]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[ 5.,  5.]], dtype=float32)

In [18]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

### Random values for variable initializations 

In [19]:
tf.random_normal([3]).eval()

array([ 0.93376452, -0.45112884, -0.56874341], dtype=float32)

In [20]:
tf.random_uniform([2]).eval()

array([ 0.13913763,  0.06281352], dtype=float32)

In [21]:
tf.random_uniform([2, 3]).eval()

array([[ 0.08339167,  0.35136676,  0.45676231],
       [ 0.10042191,  0.32939088,  0.49997854]], dtype=float32)

### Reduce Mean/Sum

In [22]:
tf.reduce_mean([1, 2], axis=0).eval() # dypte 중요

1

In [23]:
tf.reduce_mean([1., 2.], axis=0).eval() # dtype 중요

1.5

In [24]:
x = [[1., 2.],
     [3., 4.]]
tf.reduce_mean(x).eval()

2.5

In [25]:
tf.reduce_mean(x, axis=0).eval()

array([ 2.,  3.], dtype=float32)

In [26]:
tf.reduce_mean(x, axis=1).eval()

array([ 1.5,  3.5], dtype=float32)

In [27]:
tf.reduce_mean(x, axis=-1).eval() # -1 shape 상의 뒤의 axis

array([ 1.5,  3.5], dtype=float32)

In [28]:
tf.reduce_sum(x).eval()

10.0

In [29]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [30]:
tf.reduce_sum(x, axis=-1).eval()

array([ 3.,  7.], dtype=float32)

In [31]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

### Argmax with axis

In [32]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [33]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [34]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

### Reshape, squeeze, expand_dims

In [35]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [36]:
tf.reshape(t, shape=[-1, 3]).eval() # -1을 알아서 조절하라라는 뜻

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
tf.reshape(t, shape=[-1, 3]).eval().shape

(4, 3)

In [38]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [39]:
tf.reshape(t, shape=[-1, 1, 3]).eval().shape

(4, 1, 3)

In [40]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2])

In [41]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]])

### One hot

In [42]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [43]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval().shape # tf.one_hot은 자동으로 rank를 하나더 늘린다.

(4, 1, 3)

In [44]:
tf.squeeze(tf.one_hot([[0], [1], [2], [0]], depth=3).eval(), axis = 1).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

In [45]:
tf.squeeze(tf.one_hot([[0], [1], [2], [0]], depth=3).eval(), axis = 1).eval().shape

(4, 3)

In [46]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval() # shape -1 잘 활용할 것!

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

In [47]:
tf.reshape(t, shape=[-1, 3]).eval().shape

(4, 3)

### casting

In [48]:
tf.cast([1.8, 2.2, 3.3, 4.9], dtype = tf.int32).eval()

array([1, 2, 3, 4])

In [49]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

### stack 

In [50]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [51]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

### Ones and Zeros like 

In [52]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [53]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

### Zip

In [54]:
list(zip([1,2,3], [4,5,6]))

[(1, 4), (2, 5), (3, 6)]

In [55]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [56]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


### Transpose 

In [57]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [58]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [59]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [60]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [61]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
